enum_discrim_align_threshold = 40
format_code_in_doc_comments = true
hex_literal_case = "Lower"
match_block_trailing_comma = true
imports_granularity = "Module"
group_imports = "StdExternalCrate"
use_field_init_shorthand = true
